services:
  apicurio-registry:
    image: apicurio/apicurio-registry:latest-release@sha256:c9cae4c90ce46538abf673c68eb591345f23bcc6c2aa6bfd47189adcf609d8f1
    ports:
      - "127.0.0.1:8080:8080"
  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:latest-release@sha256:1fc428f4dfe9f08e08494d6855296717a8ca5ab87c9c6b1b3fafab58ede138d8
    ports:
      - "127.0.0.1:8888:8080"
    depends_on:
      - apicurio-registry
